### ISSUE TITLE
Consider using `termion::input` instead of manually parsing the keycode.

### ISSUE THREAD

**Issue by Enter-tainer** [asrcpq/tttz#1]
See https://docs.rs/termion/1.5.6/termion/input/trait.TermRead.html and http://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/#inputs.

```rust
    for c in stdin.keys() {
        // Print the key we type...
        match c.unwrap() {
            // Exit.
            Key::Char('q') => break,
            Key::Char(c)   => println!("{}", c),
            Key::Alt(c)    => println!("Alt-{}", c),
            Key::Ctrl(c)   => println!("Ctrl-{}", c),
            Key::Left      => println!("<left>"),
            Key::Right     => println!("<right>"),
            Key::Up        => println!("<up>"),
            Key::Down      => println!("<down>"),
            _              => println!("Other"),
        }

        // Flush again.
        stdout.flush().unwrap();
    }
```

`termion::input`'s keycode parser support arrow keys, which enables us to customize keymaps.

I'm happy to propose a pr to add this feature if it is acceptable.

**Comment by asrcpq** [comment]
Now you can use arrow key for piece movement.

It seems that `async_stdin` does not have keys() function. So I just manually parsed the raw ansi escape code.

Also, since a terminal cannot have keydown event. You may want to increase key repeat rate in your OS to simulate long press.

**Comment by Enter-tainer** [comment]
Oh, I forgot that `stdin` should be non-blocking. Therefore I guess that parsing by hand is the only solution. :cry: Thanks for your excellent project!
